queue_rules:
  - name: default
    conditions: []
    speculative_checks: 2
    batch_size: 5

pull_request_rules:
  - name: Automatic merge of 2+ commits on approval
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "#commits>=2"
    actions:
      queue:
        name: default
        method: merge
        commit_message_template: |
            Merge #{{number}} '{{title}}'

            {{body}}
  - name: Automatic rebase of a single commit on approval
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "#commits=1"
    actions:
      queue:
        name: default
        method: rebase
