[package]
name = "server"
version = "0.0.0"
authors = ["ChiselStrike"]
edition = "2018"

[dependencies]
convert_case = "0.4.0"
futures = "0.3.17"
hyper = "0.14.13"
log = "0.4.14"
pretty_env_logger = "0.4.0"
prost = "0.8.0"
serde_json = "1.0.68"
structopt = "0.3.23"
tokio = { version = "1.11.0", features = ["full"] }
tokio-stream = { version = "0.1.7", features = ["signal"] }
tonic = "0.5.2"

[build-dependencies]
tonic-build = "0.5.2"

[[bin]]
name = "chiseld"
path = "src/main.rs"
