[package]
name = "server"
version = "0.0.0"
authors = ["ChiselStrike"]
edition = "2018"

[dependencies]
structopt = "0.3.23"
tonic = "0.5.2"
prost = "0.8.0"
tokio = { version = "1.11.0", features = ["full"] }
hyper = "0.14.13"
convert_case = "0.4.0"
pretty_env_logger = "0.4.0"
log = "0.4.14"
serde_json = "1.0.68"
futures = "0.3.17"

[build-dependencies]
tonic-build = "0.5.2"

[[bin]]
name = "chiseld"
path = "src/main.rs"
