[package]
name = "tsc_compile"
version = "0.7.0-dev.0"
authors = ["ChiselStrike"]
edition = "2021"

[dependencies]
anyhow = "1.0"
deno_core = { path = "../third_party/deno/core" }
ureq = "2.4.0"
url = "2.2.2"

[dev-dependencies]
tempfile = "3.2.0"
tokio = { version = "1.11.0", features = ["rt-multi-thread", "macros"] }

[package.metadata.cargo-udeps.ignore]
# Used only to update the submodules
build = ["third_party"]

[build-dependencies]
anyhow = "1.0"
deno_core = { path = "../third_party/deno/core" }
third_party = { path = "../third_party" }

[lib]
name = "tsc_compile"
